PACKAGE_NAME="getac-mpmd"
PACKAGE_VERSION="1.0"
MAKE[0]="make KVERSION=${kernelver}"
CLEAN="make KVERSION=${kernelver} clean"
BUILT_MODULE_NAME[0]="getac-mpmd"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"
