// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * GETAC MPMD programmable button driver
 *
 * GETAC rugged laptops expose vendor events through an ACPI device named
 * "MPMD" with hardware ID MTC0303. The Embedded Controller raises query
 * methods that Notify(MPMD, <code>) on programmable / hotkey button
 * activity. Without a driver bound to MTC0303 these notifies are silently
 * dropped, so the buttons appear dead under Linux.
 *
 * This driver binds MTC0303 and forwards the notifies as input events.
 *
 * Observed on GETAC S410 (BIOS R1.25.070520):
 *   0x97  P2 programmable button (repeats at ~3 Hz while held)
 *
 * Observed on GETAC B360:
 *   0x92  P2 programmable button (repeats at ~3 Hz while held)
 *
 * On the B360 the EC also injects an unmapped legacy AT scancode (e0 18)
 * for the same button via the i8042 keyboard controller; that path is left
 * alone here (atkbd just logs "Unknown key" for it) since the ACPI notify
 * above is sufficient to deliver the event.
 *
 * The 0xC0..0xCB range is generated by EC query methods _Q81.._Q89, _Q6A
 * and _Q6B and is left as KEY_UNKNOWN until a button is confirmed; enable
 * module dynamic-debug to identify further buttons on a given model.
 *
 * Copyright (C) 2026 chubukou <chubukou@gmail.com>
 */

#include <linux/acpi.h>
#include <linux/input.h>
#include <linux/input/sparse-keymap.h>
#include <linux/module.h>

struct getac_mpmd_priv {
	struct input_dev *input;
};

static const struct key_entry getac_mpmd_keymap[] = {
	{ KE_KEY, 0x97, { KEY_PROG1 } },		/* P2 programmable button (S410) */
	{ KE_KEY, 0x92, { KEY_PROG1 } },		/* P2 programmable button (B360) */
	{ KE_END, 0 }
};

static void getac_mpmd_notify(struct acpi_device *adev, u32 event)
{
	struct getac_mpmd_priv *priv = acpi_driver_data(adev);

	if (!sparse_keymap_report_event(priv->input, event, 1, true))
		dev_dbg(&adev->dev, "unknown notify event 0x%02x\n", event);
}

static int getac_mpmd_add(struct acpi_device *adev)
{
	struct getac_mpmd_priv *priv;
	struct input_dev *input;
	int ret;

	priv = devm_kzalloc(&adev->dev, sizeof(*priv), GFP_KERNEL);
	if (!priv)
		return -ENOMEM;

	input = devm_input_allocate_device(&adev->dev);
	if (!input)
		return -ENOMEM;

	input->name = "GETAC MPMD programmable buttons";
	input->phys = "getac-mpmd/input0";
	input->id.bustype = BUS_HOST;

	ret = sparse_keymap_setup(input, getac_mpmd_keymap, NULL);
	if (ret)
		return ret;

	ret = input_register_device(input);
	if (ret)
		return ret;

	priv->input = input;
	adev->driver_data = priv;
	return 0;
}

static const struct acpi_device_id getac_mpmd_ids[] = {
	{ "MTC0303" },
	{ }
};
MODULE_DEVICE_TABLE(acpi, getac_mpmd_ids);

static struct acpi_driver getac_mpmd_driver = {
	.name = "getac_mpmd",
	.class = "getac",
	.ids = getac_mpmd_ids,
	.ops = {
		.add = getac_mpmd_add,
		.notify = getac_mpmd_notify,
	},
};

module_acpi_driver(getac_mpmd_driver);

MODULE_AUTHOR("chubukou <chubukou@gmail.com>");
MODULE_DESCRIPTION("GETAC MPMD (MTC0303) programmable button driver");
MODULE_LICENSE("GPL");
